name: Show Release title

on:
  release:
    types: [published]

jobs:
  show-release-title:
    runs-on: ubuntu-latest

    steps:
      - name: Print release info
        run: |
          echo "Release title: ${{ github.event.release.name }}"
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "Release notes:"
          echo "${{ github.event.release.body }}"
